### ISSUE TITLE
Booking

### ISSUE THREAD

**Issue by Hyune-c** [Hyune-c/raider50g#6]
### Entity
- [x] `Booking`: 레이드 예약
  - [x] `@Embeddable` 객체인 `Raider: 공격대원 정보` 와 `RaidInfo: 레이드 일정` 를 가집니다.
### DTO
- [x] `BookingCommand`: 예약을 위한 Input DTO
  - [x] `@Embeddable` 객체인 `Raider: 공격대원 정보` 와 `RaidInfo: 레이드 일정` 를 가집니다.
- [x] `DiscordMessage`: 디스코드에서 제공하는 `Message` 를 implement 한 DTO
### Enum
- [x] `ClassType`: 직업별 정보
- [x] `DungeonType`: 던전별 정보
### POJO
- [x] `BookingList`: Booking 들을 묶고 관리하기 위한 객체
## Service
- [x] `cancelBooking()`: 예약 취소
- [x] `makeInviteMacro()`: 공대원 초대 매크로 스크립트 만들기
## Repository
- [x] `findOne()`
- [x] `findAll()`
## API
- [x] /api/booking
  - `BookingCommand` 를 입력받아 `레이드 예약` 을 합니다
---
# WorkLog
## Phase 1
> Message 를 파싱하여 Booking 하기

- [x] BookingType, ClassType 추가
- [x] Booking 객체 추가
- [x] Test Case 추가

> Message 를 지정된 채널에 올리기
- phase2 로 변경

## Phase 2
> Domain 기준으로 분리하기
### Entity
- [x] `Booking`: 레이드 예약
  - [x] `@Embeddable` 객체인 `Raider: 공격대원 정보` 와 `RaidInfo: 레이드 일정` 를 가집니다
### DTO
- [x] `BookingCommand`: 예약을 위한 Input DTO
  - [x] `@Embeddable` 객체인 `Raider: 공격대원 정보` 와 `RaidInfo: 레이드 일정` 를 가집니다
### API
- [x] /api/booking
  - `BookingCommand` 를 입력받아 `레이드 예약` 을 합니다
### 사용한 기술
- [x] JPA 를 사용하였습니다
  - `EntityManager` 를 통해 DB 관리를 하였습니다
